Algoritmo "salariatualizado"

Var
      salarioantigo,aumento,salarioatualizado:real


Inicio
        escreva (salarioantigo)
        leia (salarioantigo)
        escreva (aumento)
        leia (aumento)
        escreva (salarioatualizado)
        leia (salarioatualizado)
        salarioatualizado<-salarioantigo+salarioantigo*percentagem/100
        escreva (salarioatualizado)

Fimalgoritmo